export const darkTheme = {
  colors: {
    borderColor: "#8B8D90",
    backgroundColor: "#1d242e",
    backgroundColorInput: "#161B22",
    colorInputBorder: "#8B8D90",
    backgroundColorSubmit: "#0095f6",
    color: "#fff",
    titleColor: "#fff",
    sideBarContainerBackgroundColor: "#1d242e",
    styledLinkColor: "#0095f6",
    body: "#161B22",
    colorInput: "#fff",
    serachBackgroundColorInput: "#161B22",
    serachBorderInput: "#8B8D90",
    headerBorder: "#8B8D90",
    footerBorder: "#DBDBDB",
    sharePostButton: "#0095F6",
    fullNameColor: "#8e8e8e",
    spinner: "#0095f6",
  },
};

export const lightTheme = {
  colors: {
    borderColor: "#dbdbdb",
    backgroundColor: "#ffffff",
    backgroundColorInput: "#fafafa",
    colorInputBorder: "#dbdbdb",
    backgroundColorSubmit: "#0095f6",
    titleColor: "#000",
    color: "#fff",
    sideBarContainerBackgroundColor: "#ffffff",
    styledLinkColor: "#0095f6",
    body: "#fafafa",
    colorInput: "#000",
    serachBackgroundColorInput: "#FAFAFA",
    serachBorderInput: "#DBDBDB",
    headerBorder: "#DBDBDB",
    footerBorder: "#DBDBDB",
    sharePostButton: "#0095F6",
    fullNameColor: "#8e8e8e",
    spinner: "#0095f6",
  },
};
